Repository test-fullautomation/robotframework-robotlog2db, pull requests merged in 2023-06, with the labels that each got.

#50 update README file: fix image issue on PyPI, introduction for installation
  README.md
  README.rst
  RobotLog2DB/RobotLog2DB.pdf
  RobotLog2DB/version.py
  packagedoc/additional_docs/History.tex
  requirements.txt
Labels: enhancement, 0.8.0

#52 Adapted date and company name
  README.rst
  RobotLog2DB/CDataBase.py
  RobotLog2DB/__init__.py
  RobotLog2DB/__main__.py
  RobotLog2DB/robotlog2db.py
  RobotLog2DB/version.py
  additions/CExtendedSetup.py
  additions/__init__.py
  config/CRepositoryConfig.py
  config/__init__.py
  dump_repository_config.py
  genpackagedoc.py
  packagedoc/additional_docs/Appendix.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.tex
  pytest/executepytest.py
  pytest/testcases/test_CBasics.py
  readme.rst2md.py
  requirements.txt
  setup.py
Labels: documentation, 0.9.0

#54 fix issue when root suite has starttime/endtime as N/A
  README.md
  RobotLog2DB/RobotLog2DB.pdf
  RobotLog2DB/robotlog2db.py
  RobotLog2DB/version.py
  packagedoc/additional_docs/History.tex
Labels: enhancement, 0.9.0
